// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1mVw7iELX9vBPrdiBIHs6ZWK8Kz33r6Q',
    appId: '1:713174537653:web:25644e110a23d68b7ff5fc',
    messagingSenderId: '713174537653',
    projectId: 'syncuwell-93185',
    authDomain: 'syncuwell-93185.firebaseapp.com',
    storageBucket: 'syncuwell-93185.appspot.com',
    measurementId: 'G-KX90QSK2V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpLZ1e7BITtO8ATeU9p57n0R1GALCkjUE',
    appId: '1:713174537653:android:b1ce7112ee63c57f7ff5fc',
    messagingSenderId: '713174537653',
    projectId: 'syncuwell-93185',
    storageBucket: 'syncuwell-93185.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX4Vp_PZrwjujApDaJmQk3_RO0f23BHhc',
    appId: '1:713174537653:ios:3092008ffc77a5447ff5fc',
    messagingSenderId: '713174537653',
    projectId: 'syncuwell-93185',
    storageBucket: 'syncuwell-93185.appspot.com',
    iosClientId: '713174537653-u9jg9m3t0lpn8o3u81cuuhmgldcj8seh.apps.googleusercontent.com',
    iosBundleId: 'com.example.syncuwell',
  );
}
